# Generated by Django 5.2.6 on 2025-09-09 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="service",
            old_name="is_active",
            new_name="status",
        ),
        migrations.RemoveField(
            model_name="service",
            name="description",
        ),
    ]
