# Generated by Django 5.2.6 on 2025-09-09 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0002_rename_is_active_service_status_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="description",
            field=models.CharField(max_length=100, null=True),
        ),
    ]
