# Generated by Django 4.2.15 on 2025-09-10 16:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0005_alter_center_center_name"),
        ("services", "0003_service_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="service",
            name="center_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="center.center",
            ),
        ),
    ]
