# Generated by Django 5.2.6 on 2025-09-09 05:11

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Appointment",
            fields=[
                (
                    "appointment_id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "booking_status",
                    models.CharField(
                        choices=[
                            ("Completed", "Completed"),
                            ("Cancelled", "Cancelled"),
                            ("Upcoming", "Upcoming"),
                        ],
                        max_length=100,
                    ),
                ),
                (
                    "transfer_letter",
                    models.ImageField(blank=True, null=True, upload_to="uploads/"),
                ),
                ("appointment_date", models.DateField()),
            ],
        ),
    ]
