# Generated by Django 5.2.6 on 2025-09-09 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("appointment", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="appointment",
            name="appointment_date",
            field=models.DateTimeField(),
        ),
    ]
