# Generated by Django 4.2.15 on 2025-09-10 08:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0004_alter_center_image_path"),
        ("services", "0003_service_description"),
        ("appointment", "0003_alter_appointment_appointment_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="appointment",
            name="center_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="center.center",
            ),
        ),
        migrations.AddField(
            model_name="appointment",
            name="service_id",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.service",
            ),
        ),
    ]
