# Generated by Django 5.2.6 on 2025-09-08 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ARVAvailability",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "arv_availability",
                    models.CharField(
                        choices=[
                            ("available", "Available"),
                            ("not available", "Not available"),
                        ],
                        max_length=20,
                    ),
                ),
                ("last_updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
