# Generated by Django 5.2.6 on 2025-09-08 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="center",
            name="address",
            field=models.CharField(default="unknown", max_length=50),
        ),
    ]
