# Generated by Django 5.2.6 on 2025-09-08 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0002_center_address"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="latitude",
            field=models.FloatField(default=0.0),
        ),
        migrations.AlterField(
            model_name="center",
            name="longitude",
            field=models.FloatField(default=0.0),
        ),
    ]
