# Generated by Django 4.2.15 on 2025-09-10 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0003_alter_center_latitude_alter_center_longitude"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="image_path",
            field=models.ImageField(blank=True, null=True, upload_to="uploads/"),
        ),
    ]
