# Generated by Django 4.2.15 on 2025-09-10 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("center", "0004_alter_center_image_path"),
    ]

    operations = [
        migrations.AlterField(
            model_name="center",
            name="center_name",
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
