# Generated by Django 4.2.14 on 2025-10-04 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("center", "0005_alter_center_center_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="center",
            name="operating_hours",
        ),
        migrations.AddField(
            model_name="center",
            name="closing_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="opening_time",
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="center",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
